### ISSUE TITLE
Write tests that verify the json graph output structures are correct.

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/Networkx-To-Lava-NC#67]
- [x] Delete the results folder content manually at the start of `__main__` (temporarily).
- [x] Fix the tests in:
- [x] Write a test that verifies the graph output structure is correct. (Use a minimal/dedicated test, this has already been created.).

**Comment by a-t-0** [comment]
The json graph output structure should be:
experiment setting
run setting
graphs.

Depending on the run settings and experiment settings, the graphs should be:
...
...

And depending on the level of completion, these graphs should have a stage index:
1,2,3,4.

**Comment by a-t-0** [comment]
Fix everything that uses `f"stage_{stage}"`. It should not be used, the stage completion is indicated with a list inside the graph under key: `completed_stages = {..}`


```
for stage in stages:
        if f"stage_{stage}" in output_dict["graphs_dict"]:
            restored_graphs_dict[f"stage_{stage}"] = output_dict[
                "graphs_dict"
            ][f"stage_{stage}"]
            
            ```
            And another one. CTRL+F

- [ ] Write test to verify the `completed_stages` key never contains duplicate values.

**Comment by a-t-0** [comment]
Up next. Make sure the main.py outputs the expected dictionaries (if export_snns is false).

**Comment by a-t-0** [comment]
# Verify the graph types are as expected.

**Comment by a-t-0** [comment]
```
# TODO: check if the overwrite is True,
            # TODO: check if the graphs already are loaded from file.
            # TODO: check if the graphs can be loaded from file,

            # TODO: Verify the (incoming (and loaded)) graph types are as expected.
            ```

**Comment by a-t-0** [comment]
The alg props are modified during test TTTF. This leads to a different sim_time at different times in the test (while creating the dummy images, sim duration =55, and while testing if stage 3 is completed, sim_duration =94. 

-[ ]  Determine why the alg props are not set in the test.
-[ ]  Determine why setting the alg props leads to a different sim duration.
-[ ]  Throw error if alg props are not set whilst getting sim duration.
-[ ]  Ensure alg props are set in test before creating dummy images
